name = "Snowballs_el_edition"
author = "SilentBear"
version = "14.8.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88c2a75b21c94bcdb5189a49027b45527c39c885007e6b13ba2007c8295322b3"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
