name = "Snowballs_el_edition"
author = "SilentBear"
version = "14.8.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb4a16bb300f03001bc3ce2d4cb502ec9e4569cabf67aabedb852f5f188b3c4e"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
