name = "Snowballs_el_edition"
author = "SilentBear"
version = "14.8.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59bf4dd32694f5f32b4a3749892b8bbf4e13eda5d22c6291a1c60dd1a7ddb1d4"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
